blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls', namespace='posts')),
    path('categorias/', include('categoria.urls', namespace='categorias')),
    path('comentario/', include('comentario.urls', namespace='comentarios')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categoria/urls.py
from django.urls import path

from .views import CategoriaList, CategoriaDetalle,CategoriaCreate


app_name = 'Categoria'
urlpatterns = [
    path('', CategoriaList.as_view(), name='list'),
    path('create/', CategoriaCreate.as_view(), name='create'),
    path('<slug:slug>/', CategoriaDetalle.as_view(), name='detail'),
]

categoria/models.py
from django.db import models
from django.template.defaultfilters import slugify

from .managers import PostCategoryManager


from datetime import datetime

class Categoria(models.Model):
    
    nombre = models.CharField(
        max_length=100,
        null=False,
        blank=False
    )
    
    estado = models.BooleanField(
        default=True
    )

    fecha_creacion = models.DateField(
        auto_now=False,
        auto_now_add=True
    )

    slug = models.SlugField('slug')

    activos = PostCategoryManager()

    def __str__(self):
        return self.nombre
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super(Categoria, self).save(*args, **kwargs)

categoria/forms.py
import re
from django.forms import ModelForm
from.models import Categoria

class CategoriaForm(ModelForm):
    
    class Meta:
        model = Categoria
        fields = [
            'nombre'
        ]

    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

categoria/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.models import LogEntry, ADDITION
from django.contrib.admin.options import get_content_type_for_model


from .models import Categoria
from post.models import Post
from .forms import CategoriaForm

class CategoriaList(ListView):
    model = Categoria
    template_name = "categorias/list.html"
    queryset = Categoria.activos.all()


class CategoriaDetalle(DetailView):
    model = Categoria
    template_name = "categorias/detail.html"
    queryset = Categoria.activos.all()

    def get_context_data(self, **kwargs):
        contexts = super().get_context_data(**kwargs)
        contexts.update(posts=Post.estados.actives().filter(categoria__in=[self.object.id]))
        return contexts


class CategoriaCreate(LoginRequiredMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy('categorias:list')
    template_name = 'categorias/create.html'

    def form_valid(self, form):
        self.object = form.save()
        LogEntry.objects.log_action(
            user_id=self.request.user.pk,
            content_type_id=get_content_type_for_model(self.object).pk,
            object_id=self.object.pk,
            object_repr=str(self.object),
            action_flag=ADDITION,
            change_message='Post Creado: {}'.format(self.object.nombre),
        )
        return super().form_valid(form)

templates/categorias/create.html
{% extends 'base.html' %}
{% load static %}

{% block main_title %}
    Crear una categoría
{% endblock main_title %}

{% block main_subtitle %}
    {{ object.titulo }}
{% endblock main_subtitle %}

{% block container %}
<form action="{% url 'categorias:create' %}" method="POST">
    {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {{ field.label_tag }}
        <div class="form-group">
            {{ field }}
            {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    <div class="modal-footer">
        <button id = "IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
        <a href="{% url 'categorias:list' %}"
            class="btn btn-secondary">Cancelar</a>
    </div>
</form>

{% endblock container %}

templates/categorias/detail.html
{% extends 'base.html' %}


{% block main_title %}{{ object.nombre }}{% endblock main_title %}
{% block main_subtitle %}{{ object.descripcion }}{% endblock main_subtitle %}

{% block container %}
    
            {% for post in posts %}
            <div class="post-preview">
                <a href="{% url 'posts:detail' post.slug %}">
                    <h5 class="post-title">
                        {{ post.titulo }}
                    </h5>
                    <h3 class="post-subtitle">
                        {{ post.descripcion }}
                    </h3>
                </a>
                <p class="post-meta">Creado: {{ post.fecha_creacion }}</p>
            </div>
            <hr>
            {% empty %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">No se han encontrado datos.</h1>
                    </div>
                </div>

            {% endfor %}
       
{% endblock container %}

templates/categorias/list.html
{% extends 'base.html' %}

{% block container %}
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for categoria in object_list %}
            <div class="categoria-preview">
                <a href="{% url 'categorias:detail' categoria.slug %}">
                    <h2 class="categoria-title">
                        {{ categoria.nombre }}
                    </h2>
                    <h3 class="categoria-subtitle">
                        {{ categoria.descripcion }}
                    </h3>
                </a>
                <p class="categoria-meta">Creado: {{ categoria.fecha_creacion }}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- Pager -->
            <div class="clearfix">
                <a class="btn btn-primary float-right" href="#">Older categorias &rarr;</a>
            </div>
        </div>
    </div>
{% endblock container %}