blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls', namespace='posts')),
    path('categorias/', include('categoria.urls', namespace='categorias')),
    path('comentario/', include('comentario.urls', namespace='comentarios')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from .views import PostList, MisPost, PostDetalle,PostCreate, PostUpdate, PostDelete

app_name = 'Post'
urlpatterns = [
    path('', PostList.as_view(), name= 'list'),
    path('mis-post/', MisPost.as_view(), name= 'list-mis-post'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug:slug>/update', PostUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', PostDelete.as_view(), name='delete'),
    path('<slug:slug>/', PostDetalle.as_view(), name='detail'),
]

comentario/models.py
from django.db import models

from post.models import Post
from usuario.models import Usuario

class Comentario(models.Model):
    comentario = models.CharField(
        max_length=500, 
        blank=False, 
        null=False)

    post = models.ForeignKey(
        Post, on_delete=models.CASCADE 
    )

    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE
    )
    

post/models.py
from django.db import models
from django.template.defaultfilters import slugify

from ckeditor.fields import RichTextField
from usuario.models import Usuario
from categoria.models import Categoria
from datetime import datetime

from .managers import PostManager

class Post(models.Model):
    titulo = models.CharField(
        max_length = 100,
        blank = False,
        null = False
    )

    slug = models.SlugField('slug', blank=True, null=True)

    descripcion = models.CharField(
        max_length = 500,
        blank = False,
        null = False
    )

    contenido = RichTextField()

    imagen = models.ImageField(
        blank=True,
        null = True
    )

    autor = models.ForeignKey(
        Usuario,on_delete = models.CASCADE,
        null = True, blank = True
    )

    estado = models.BooleanField('Activo',
        default=True
    )

    fecha_creacion = models.DateField(
        auto_now=False, 
        auto_now_add=True
    )

    fecha_inicio_publicacion = models.DateField(
        default=datetime.now
    )

    fecha_fin_publicacion = models.DateField(
        blank=True,
        null=True
    )

    categoria = models.ManyToManyField(Categoria)


    estados = PostManager()

    def mostrar_estado(self):
        if self.estado:
            mostrar_estado = "Activo"
        else:
            mostrar_estado = "Inactivo"
        
        return mostrar_estado

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        super(Post, self).save(*args, **kwargs)

post/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.admin.models import LogEntry, ADDITION, DELETION
from django.contrib.admin.options import get_content_type_for_model
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from .models import Post
from .form import PostForm

from comentario.models import Comentario
from comentario.forms import ComentarioForm



class PostList(ListView):
    model = Post
    template_name = "post/list.html"
    queryset = Post.estados.actives()
    

    def get_queryset(self):
        buscar = self.request.GET.get("buscar")
        
        queryset = super().get_queryset()
        if buscar:
            queryset = queryset.filter(
                Q(titulo__icontains=buscar) |
                Q(autor__first_name__icontains= buscar)|
                Q(categoria__nombre__icontains= buscar)
            ).distinct()
        return queryset


class MisPost(PostList):
    def get_queryset(self):
        qs = super().get_queryset().filter(autor_id=self.request.user.id)
        return qs


class PostDetalle(DetailView):
    model = Post
    template_name = "post/detail.html"
    queryset = Post.estados.actives()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        inits = {
            'usuario': self.request.user.id,
            'post': self.object.id
        }
        context.update(form=ComentarioForm(inits))
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')
    template_name = 'post/create.html'

    def get_initial(self):
        init = super(PostCreate, self).get_initial()
        user_id = self.request.user.id
        init.update(autor=user_id)
        return init

    def form_valid(self, form):
        self.object = form.save()
        LogEntry.objects.log_action(
            user_id=self.request.user.pk,
            content_type_id=get_content_type_for_model(self.object).pk,
            object_id=self.object.pk,
            object_repr=str(self.object),
            action_flag=ADDITION,
            change_message='Post Creado: {}'.format(self.object.titulo),
        )
        return super().form_valid(form)


class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')
    template_name = 'post/update.html'

    def get_success_url(self):
        self.success_url = reverse_lazy('posts:detail', kwargs={'slug': self.object.slug})
        return super().get_success_url()

    def form_valid(self, form):
        self.object = form.save()
        LogEntry.objects.log_action(
            user_id=self.request.user.pk,
            content_type_id=get_content_type_for_model(self.object).pk,
            object_id=self.object.pk,
            object_repr=str(self.object),
            action_flag=ADDITION,
            change_message='Post Creado: {}'.format(self.object.titulo),
        )
        return super().form_valid(form)


class PostDelete(DeleteView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')
    template_name = 'post/delete.html'

    def get_success_url(self):
        self.success_url = reverse_lazy('posts:list')
        return super().get_success_url()
        
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        LogEntry.objects.log_action(
                user_id=self.request.user.pk,
                content_type_id=get_content_type_for_model(self.object).pk,
                object_id=self.object.pk,
                object_repr=str(self.object),
                action_flag=DELETION,
                change_message='Post Creado: {}'.format(self.object.titulo),
            )
        return HttpResponseRedirect(success_url)



        

templates/post/create.html
{% extends 'base.html' %}
{% load static %}

{% block main_title %}
Crear un post
{% endblock main_title %}

{% block main_subtitle %}
{{ object.titulo }}
{% endblock main_subtitle %}

{% block container %}
<form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
        {% for field in form.visible_fields %}
    {{ field.label_tag }}
    <div class="form-group">
        {{ field }}
        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
    </div>

    {% endfor %}
    <hr>
    <div class="modal-footer">
        <button id="IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
        <a href="{% url 'posts:list' %}" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

{% endblock container %}

templates/post/delete.html
{% extends "base.html" %}
{% load static %}

{% block main_title %}
{{object.titulo}}
{% endblock main_title %}

{% block container %}
<div id="content-wrapper">
        <br><br><br>
        <div class="central_container_form">
            <h1 class="text-center">¿Realmente deseas eliminar el post?</h1>
            <br><br><br>
            <form action="{% url 'posts:delete' object.slug %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                    <button class="btn btn-danger" type="submit">Confirmar</button>               
                    <a href="{% url 'posts:list' %}" class="btn btn-secondary">Cancelar</a>                
                </div>
            </form>
        </div>
    </div>
    
{% endblock container %}

templates/post/detail.html
{% extends 'base.html' %}
{% load static %}



{% block main_title %}
{{ object.titulo }}
{% endblock main_title %}

{% block main_subtitle %}
{{ object.titulo }}
{% endblock main_subtitle %}

{% if object.img %}
    {% block img %}{% get_media_prefix %}{{object.imagen}}{% endblock img %}
{% endif %}

{% block container %}
{{object.contenido | safe }}
<div class="modal-footer">  
         
        {% if object.autor.id == request.user.id or request.user.is_staff %}
        <a href="{% url 'posts:delete' object.slug %}" id="IdEliminar" class="btn btn-danger">Eliminar post</a>   
        <a href="{% url 'posts:update' object.slug %}" id="IdModificar" class="btn btn-warning" >Modificar post</a>
        {% endif %}
    </div>
{% endblock container %}

{% block comentarios %}
{%if request.user.is_authenticated %}
<form action="{% url 'comentario:create' %}" method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {{ field.label_tag }}
        <div class="form-group">
            {{ field }}
            {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
    
        {% endfor %}
        <hr>
        <div class="modal-footer">  
            <button id="IdAgregar" class="btn btn-success" type="submit">Agregar comentario</button>
        </div>
</form>
{% endif %}
<br>
<ul class="list-unstyled">
{% for comentario in object.comentario_set.all %}
    <li class="media">
        <div class="media-body">
            <h5 class="mt-0 mb-1">{{comentario.usuario.first_name}}</h5>
            {{comentario.comentario}}
        </div>
    </li>
    <br>
    {% endfor %}
</ul>
{% endblock comentarios %}

templates/post/list.html
{% extends 'base.html' %}

{% block container %}
<div class="container">
    <div class="row">
        <div class="col-md-12 search">
            <form method="GET">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control" placeholder="Buscar..." name="buscar">
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" class="btn btn-success">Buscar</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in object_list %}
            <div class="post-preview">
                <a href="{% url 'posts:detail' post.slug %}">
                    <h2 class="post-title">
                        {{ post.titulo }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ post.descripcion }}
                    </h3>
                </a>
                <p class="post-meta">Publicado por <strong>{{ post.autor }}</strong> el mes de {{ post.fecha_creacion }}</p>
            </div>
            <hr>
            {% empty %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">No se han encontrado datos.</h1>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock container %}

templates/post/update.html
{% extends "base.html" %}
{% load static %}

{% block main_title %}
{{object.titulo}}
{% endblock main_title %}

{% block container %}
<div id="content-wrapper">
    <br><br>
    <form class="central_container_form needs-validation was-validatedx" action="{% url 'posts:update' object.slug %}"
        method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Guardar</button>
            <a href="{% url 'posts:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock container %}