blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls', namespace='posts')),
    path('categorias/', include('categoria.urls', namespace='categorias')),
    path('comentario/', include('comentario.urls', namespace='comentarios')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from .views import PostList, MisPost, PostDetalle,PostCreate, PostUpdate, PostDelete

app_name = 'Post'
urlpatterns = [
    path('', PostList.as_view(), name= 'list'),
    path('mis-post/', MisPost.as_view(), name= 'list-mis-post'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug:slug>/update', PostUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', PostDelete.as_view(), name='delete'),
    path('<slug:slug>/', PostDetalle.as_view(), name='detail'),
]

usuario/urls.py
from django.urls import path

from .views import LoginView, LogoutView, AccountCreate, AccountUpdate


app_name = 'usuario'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreate.as_view(), name='create'),
    path('update/<int:pk>/', AccountUpdate.as_view(), name='update'),
]

templates/components/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:list' %}">Roiback Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:list' %}">
                        Inicio
                    </a>
                </li>
                {% for categoria in categorias %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'categorias:detail' categoria.slug %}">
                            {{ categoria.nombre }}
                        </a>
                    </li>
                {% endfor %}

                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Acciones</a>
                        <div class="dropdown-menu">
                          {%if request.user.is_authenticated %}
                          <a class="dropdown-item" href="{% url 'posts:list-mis-post' %}">Mis post</a>
                          <a class="dropdown-item" href="{% url 'posts:create' %}">Crear un post</a>
                          <div class="dropdown-divider"></div>
                          {%if request.user.is_staff %}
                          <a class="dropdown-item" href="{% url 'categorias:create' %}">Crear una categoria</a>
                          <div class="dropdown-divider"></div>
                          {% endif %}
                          <a class="dropdown-item" href="{% url 'usuario:update' request.user.pk %}">Actualizar Cuenta</a>
                          <a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar sesión</a>
                          {% else %}
                          <a class="dropdown-item" href="{% url 'usuario:login' %}">Iniciar sesión</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="">Crear un cuenta</a>
                          {% endif %}
                        </div>                       
            </ul>
        </div>
    </div>
</nav>